version: '3'
services:
  db:
    image: mysql:5.7.20
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/blend
      - public-data:/blend/public
      - tmp-data:/blend/tmp
      - log-data:/blend/log
    environment:
      RAILS_ENV: development
    depends_on:
      - db

volumes:
  mysql_data:
  public-data:
  tmp-data:
  log-data:
