slack:
  webhook_url: https://hooks.slack.com/services/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

site:
  times_car_plus:
    site_name: タイムズ カー プラス
    root_url: https://plus.timescar.jp/
    crawling_url: https://plus.timescar.jp/car/
    category: car_share
    selector:
      car_list:
        basic_class: div#d_page > div.contents > section.main > div.main-wide > div.car > div.aboutcar > div.carlist > dl:nth-child(n).clearfix
        premium_class: div#d_page > div.contents > section.main > div.main-wide > div.car > div.aboutcar.hide > div.carlist > dl:nth-child(n).clearfix
      price:
        basic_class: "#cont01 > h2 > span.place"
        premium_class: "#cont02 > h2 > span.place"
      car_name: dd.mb5 > p.name > span:not(.ic_ev)
      ridable_number: dd.mb5 > ul > li
      image: dt > a.alpha > img
      station_link: div.car_bt_area > p.station-btn > a.alpha
      station:
        paginate_link: goNext
        name: span#stationNm
        address: span#adr1
  akippa:
    site_name: akippa
    root_url: https://www.akippa.com/
    crawling_url: https://www.akippa.com/kanto/
    category: parking
    selector:
      first_select: body > div.container > main > div.container > main > section.spot-region > div:nth-child(n) > ul.spot-list > li:nth-child(n) > a
      second_select: div#spot-parking-list > a
      station_name: body > div.parking-detail-title > div.container > main > section.box-container > div.parking-title-section > div.title > h2
      price: body > div.parking-detail-title > div.container > main > section.box-container > div.parking-title-section > div.info > div.detail > p.parking-price > .parking-fee
      address: div.col2-container > div.col2-container-left > main > section:nth-child(5) > div.box.parking-detail-info > div.address > p:nth-child(2)
      car_type: body > div.col2-container > div.col2-container-left > main > section:nth-child(3) > div.box.parking-detail-cartype > ul.parking-detail-list > li:nth-child(n) > p:not(.disabled):first-of-type
      image: body > div.col2-container > div.col2-container-left > main > section:nth-child(1) > div.box.parking-detail-photo > div.photo-body > div:first-child > img
  nokisaki_parking:
    site_name: 軒先パーキング
    root_url: https://parking.nokisaki.com/
    crawling_url: https://parking.nokisaki.com/
    category: parking
    selector:
      first_select: div#wrapper > div.container.main.one.pages_display > div.main > div.lower > div:nth-child(17) > div.recommend.prefectures > div.content > ul > li:nth-child(2) > a:nth-child(n)
      second_select: div#wrapper > div.container.main.one.prefectures_display > div.main > div.recommend.spots > div.content > a:nth-child(n)
      third_select: div#list_item.searchResultItem > a:nth-child(n)
      price: div.list_box > div.list_box_right > p.list_box_yen > strong
      station_name: div#spaceWrapper > div.sectionTitle > span:not([style])
      address: div#spaceWrapper > div.sectionContent > div.titleArea > p.address
      car_type: div#spaceWrapper > div.sectionContent > div.leftColumn > table:first-of-type > tbody > tr:last-child > td
      image: div#photoSlide > ul.slides > li:first-child > img
  leeap:
    site_name: leeap
    root_url: https://leeap.jp/
    crawling_url: https://leeap.jp/
    category: clothes
    selector:
      wrapper: div#coordinateArea > div.slideOuter > div.inner > ul.coord-slide li
      image: img
      type: div.coord_caption_wrap > a > p
  mechakari:
    site_name: MECHAKARI
    root_url: https://mechakari.com/
    crawling_url: https://mechakari.com/web/list/coord?brandId=CC010
    category: clothes
    selector:
      bland_list: div#footer.footer > nav.footer-brand > div.footer-brand__inner > div.footer-brand__content > ul.footer-brand__list > li:nth-child(n) > a.footer-brand__item-trigger
      product: main > .page-collection__content > .section-collection > ul.section-collection__list > li.section-collection__item
      image: a.section-collection__item-trigger > div.section-collection__image > div.section-collection__image-photo
      name: a.section-collection__item-trigger > .section-collection__name > span
      bland_name: a.section-collection__item-trigger > .section-collection__brand > span
      pagination: body > main > div.page-collection__content > div.section-collection > div.section-collection__footer > div.paginator > div.paginator__prevnext.paginator__prevnext--next > a.paginator__prevnext-trigger
