site:
  times_car_plus:
    site_name: タイムズ カー プラス
    root_url: https://plus.timescar.jp/
    crawling_url: https://plus.timescar.jp/car/
    category: car_share
    selector:
      car_list:
        basic_class: div#d_page > div.contents > section.main > div.main-wide > div.car > div.aboutcar > div.carlist > dl:nth-child(n).clearfix
        premium_class: div#d_page > div.contents > section.main > div.main-wide > div.car > div.aboutcar.hide > div.carlist > dl:nth-child(n).clearfix
      price:
        basic_class: "#cont01 > h2 > span.place"
        premium_class: "#cont02 > h2 > span.place"
      car_name: dd.mb5 > p.name > span:not(.ic_ev)
      ridable_number: dd.mb5 > ul > li
      image: dt > a.alpha > img
      station_link: div.car_bt_area > p.station-btn > a.alpha
      station:
        paginate_link: goNext
        name: span#stationNm
        address: span#adr1
  akippa:
    site_name: akippa
    root_url: https://www.akippa.com/
    crawling_url: https://www.akippa.com/kanto/
    category: parking
    selector:
      first_select: body > div.container > main > div.container > main > section.spot-region > div:nth-child(n) > ul.spot-list > li:nth-child(n) > a
      second_select: div#spot-parking-list > a
      station_name: body > div.parking-detail-title > div.container > main > section.box-container > div.parking-title-section > div.title > h2
      price: body > div.parking-detail-title > div.container > main > section.box-container > div.parking-title-section > div.info > div.detail > p.parking-price > .parking-fee
      address: div.col2-container > div.col2-container-left > main > section:nth-child(5) > div.box.parking-detail-info > div.address > p:nth-child(2)
      car_type: body > div.col2-container > div.col2-container-left > main > section:nth-child(3) > div.box.parking-detail-cartype > ul.parking-detail-list > li:nth-child(n) > p:not(.disabled):first-of-type
      image: body > div.col2-container > div.col2-container-left > main > section:nth-child(1) > div.box.parking-detail-photo > div.photo-body > div:first-child > img

